name = "DomainSetsExtensions"
uuid = "7501f4a2-640c-4ef3-8d6f-c047c4e0a712"
authors = ["Daan Huybrechs <daan.huybrechs@kuleuven.be> and contributors"]
version = "0.0.1"

[deps]
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"

[weakdeps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Intervals = "d8418881-c3e1-53bb-8760-2df7ec849ed5"

[extensions]
DomainSetsGeometryBasicsExt = "GeometryBasics"
DomainSetsIntervalsExt = "Intervals"

[compat]
DomainSets = "0.7.3"
GeometryBasics = "0.4"
Intervals = "1.10"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "GeometryBasics", "Intervals"]
